Update OpenWrt-Matrix.yml

diff --git a/.github/workflows/OpenWrt-Matrix.yml b/.github/workflows/OpenWrt-Matrix.yml
--- a/.github/workflows/OpenWrt-Matrix.yml
+++ b/.github/workflows/OpenWrt-Matrix.yml
@@ -4,6 +4,10 @@ name: OpenWrt-Matrix
 on:
   workflow_call:
     inputs:
+      lan_ip:
+        required: false
+        type: string
+        default: "192.168.1.1"
       targets:
         required: true
         type: string
@@ -19,6 +23,11 @@ on:
 
   workflow_dispatch:
     inputs:
+      lan_ip:
+        description: "Default LAN IP, default: 192.168.1.1"
+        required: false
+        type: string
+        default: "192.168.1.1"
       targets:
         description: "Select target platforms (comma separated, e.g. R2C,R2S,R3S,R4S,X86 ;leave blank for all, case-insensitive)"
         required: false
@@ -186,10 +195,24 @@ jobs:
 
       - name: Prepare Package
         working-directory: ${{ github.workspace }}/openwrt
+        env:
+          LAN_IP_INPUT: ${{ inputs.lan_ip }}
         run: |
           cp -r ../SCRIPTS/. ./
           /bin/bash 02_prepare_package.sh
           /bin/bash 02_target_only.sh
+
+          ### 默认 LAN IP ###
+          LAN_IP="${LAN_IP_INPUT:-192.168.1.1}"
+    
+          if echo "$LAN_IP" | grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}$'; then
+            echo "Set default LAN IP to ${LAN_IP}"
+            sed -i "s/192.168.1.1/${LAN_IP}/g" package/base-files/files/bin/config_generate
+          else
+            echo "Invalid LAN IP: ${LAN_IP}"
+            exit 1
+          fi
+
           /bin/bash 04_remove_upx.sh
 
       - name: QTMDFW4
