Update OpenWrt-Matrix.yml

diff --git a/.github/workflows/OpenWrt-Matrix.yml b/.github/workflows/OpenWrt-Matrix.yml
--- a/.github/workflows/OpenWrt-Matrix.yml
+++ b/.github/workflows/OpenWrt-Matrix.yml
@@ -204,10 +204,18 @@ jobs:
 
           ### 默认 LAN IP ###
           LAN_IP="${LAN_IP_INPUT:-192.168.1.1}"
-    
-          if echo "$LAN_IP" | grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}$'; then
+          
+          if echo "$LAN_IP" | grep -Eq '^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$'; then
             echo "Set default LAN IP to ${LAN_IP}"
-            sed -i "s/192.168.1.1/${LAN_IP}/g" package/base-files/files/bin/config_generate
+          
+            if grep -qE 'lan\) ipad=\$\{ipaddr:-"[^"]+"\} ;;' package/base-files/files/bin/config_generate; then
+              sed -i -E 's#lan\) ipad=\$\{ipaddr:-"[^"]+"\} ;;#lan) ipad=${ipaddr:-"'"$LAN_IP"'"} ;;#g' package/base-files/files/bin/config_generate
+              grep -n 'lan) ipad=' package/base-files/files/bin/config_generate
+            else
+              echo "LAN default IP pattern not found in config_generate"
+              grep -n 'ipad=' package/base-files/files/bin/config_generate || true
+              exit 1
+            fi
           else
             echo "Invalid LAN IP: ${LAN_IP}"
             exit 1
